config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'games#index'
  
  resources :games do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many_attached :images
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :os

  validates :title, presence: true
  validates :images, presence: true
  validates :text, presence: true
  validates :genre_id, presence: true
  validates :os_id, presence: true
  validates :price, presence: true
end

app/models/genre.rb
class Genre < ActiveHash::Base
  include ActiveHash::Associations
  has_many :games

  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'RPG' },
    { id: 3, name: 'アクションRPG' },
    { id: 4, name: 'アクション' },
    { id: 5, name: 'オープンワールド' },
    { id: 6, name: 'MO・MMO' },
    { id: 7, name: 'FPS' },
    { id: 8, name: 'アドベンチャー' },
    { id: 9, name: 'シミュレーション' },
    { id: 10, name: 'ストラテジー' },
    { id: 11, name: 'レース' },
    { id: 12, name: 'スポーツ' },
    { id: 13, name: 'リズム' },
    { id: 14, name: 'ホラー' },
    { id: 15, name: 'シューティング' },
    { id: 16, name: 'カード' }
  ]
  end

app/models/os.rb
class Os < ActiveHash::Base
  include ActiveHash::Associations
  has_many :games

  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'PCゲーム' },
    { id: 3, name: 'ソーシャルゲーム' },
    { id: 4, name: 'コンシューマーゲーム' }
  ]
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
    @game = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def update
    if @game.update(game_params)
      redirect_to game_path(@game.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @game.destroy
    redirect_to root_path
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @game.user_id
  end

  def game_params
    params.require(:game).permit(:title, :text, :genre_id, :brand, :os_id, :official, :price, { images: [] }).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('' , size: '185x50'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @game, local: true do |f| %>

    <%= render 'shared/error_messages', model:@game %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'game[images][]', id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          ブランド
        </div>
        <%= f.text_area :brand, class: "select-box", id: "item-sales-status" %>
                <div class="weight-bold-text">
          OS
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:os_id, Os.all, :id, :name, {}, {class: "select-box", id: "item-sales-status"}) %>
        <div class="weight-bold-text">
          公式サイトリンク
        </div>
        <%= f.text_area :official, class: "select-box", id: "item-sales-status" %>
      </div>
    </div>
    <%# /商品の詳細 %>
    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', game_path(@game.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/games/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「話題のゲーム情報サイト」帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      話題のゲーム情報サイト
    </h2>
    <p class='service-explain'>
      好きなゲームと出会える
    </p>
    <p class='service-explain'>
      各情報サイトにリンク
    </p>
    <div class='store-btn'>
      <%= link_to image_tag("", class:"apple-btn"), "#" %>
      <%= link_to image_tag("", class:"google-btn"), "#" %>
    </div>
  </div>
  <%# /画面上部の「話題のゲーム情報サイト」帯部分  %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
      話題のタイトル
    </div>
    <ul class='item-lists'>

      <% @game.each do |game| %>
        <li class='list'>
          <%= link_to game_path(game.id) do %>
            <div class='item-img-content'>
              <div class='item-info'>
                <h3 class='item-name'>
                  <%= game.title %>
                </h3>
                <% if game.images.attached? %>
                  <% game.images.each do |image| %>
                    <%= image_tag image, class: "item-img" %>
                  <% end %>
                <% end %>
              </div>

              <div class='item-price'>
                <span><%= game.price %>円<br></span>
                <div class='star-btn'>
                  <%= image_tag "", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>

      <% if @game.empty? %>
        <li class='list'>
          <%= link_to "#" do %>
            <div class='item-info'>
              <h3 class='item-name'>
                変なゲーム
              </h3>
            </div>
            <%= image_tag "https://tech-master.s3.amazonaws.com/uploads/curriculums/images/Rails1-4/sample.jpg", class: "item-img" %>
            <div class='item-info'>
              <div class='item-price'>
                <span>無料<br>(税込み)</span>
                <div class='star-btn'>
                  <%= image_tag "", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
  <%= link_to(new_game_path, class: 'purchase-btn') do %>
    <span class='purchase-btn-text'>出品する</span>
    <%= image_tag '' , size: '185x50' ,class: "purchase-btn-icon" %>
  <% end %>
<%= render "shared/footer" %>

app/views/games/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with(model: @game, local: true, html: { multipart: true }) do |f| %>
    <%= render 'shared/error_messages', model: @game %>
    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>
      <div id="previews"></div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :images, name: 'game[images][]', id: "item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class: "items-text", id: "item-name", placeholder: "商品名（必須 40文字まで)", maxlength: "40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          概要
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :text, class: "items-text", id: "item-info", placeholder: "商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows: "7" ,maxlength: "1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>
    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class: "select-box", id: "item-category"}) %>
        <div class="weight-bold-text">
          ブランド
        </div>
        <%= f.text_area :brand, class: "select-box", id: "item-sales-status" %>
        <div class="weight-bold-text">
          OS
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:os_id, Os.all, :id, :name, {}, {class: "select-box", id: "item-sales-status"}) %>
        <div class="weight-bold-text">
          公式サイトリンク
        </div>
        <%= f.text_area :official, class: "select-box", id: "item-sales-status" %>
      </div>
    </div>
    <%# /商品の詳細 %>
    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class: "price-input", id: "item-price", placeholder: "例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
          </span>
        </div>
      </div>
    </div>
    <%# /販売価格 %>
    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている出品、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        またブランド品でシリアルナンバー等がある場合はご記載ください。
        <a href="#">偽ブランドの販売</a>
        は犯罪であり処罰される可能性があります。
      </p>
      <p class="sentence">
        また、出品をもちまして
        <a href="#">加盟店規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "登録する" ,class: "sell-btn" %>
      <%= link_to 'もどる', root_path, class: "back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/games/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @game.title %>
    </h2>
    <div class="item-img-content">
      <% if @game.images.attached? %>
        <% @game.images.each do |image| %>
          <%= image_tag image, class: "item-box-img" %>
        <% end %>
      <% end %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= "¥#{@game.price}" %>
      </span>
      <span class="item-postage">
        <%= @game.genre.name %>
      </span>
    </div>

    <% if user_signed_in? %>
      <% if current_user.id == @game.user.id %>
        <%= link_to '商品の編集', edit_game_path(@game.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to '削除', game_path(@game.id), data: { turbo_method: :delete }, class:"item-destroy" %>
      <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @game.text %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">使用OS</th>
          <td class="detail-value"><%= @game.os.name %></td>
        </tr>
        <tr>
          <th class="detail-item">ブランド</th>
          <td class="detail-value"><%= @game.brand %></td>
        </tr>
        <tr>
          <th class="detail-item">公式サイト</th>
          <td class="detail-value"><%= link_to @game.official, @game.official, target: "blank" %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする</span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @game.genre.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameNow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("", class:"apple-btn"), "#" %>
    <%= link_to image_tag("", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'ジャンル', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
      <li><%= link_to '新着', "#", class: "new-list" %></li>
    </ul>
    <% if user_signed_in? %>
      <ul class='lists-right'>
          <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete}, class: "logout" %></li>
      </ul>
    <% else %>
      <ul class='lists-right'>
          <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      </ul>
    <% end %>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>